### ISSUE TITLE
Rotation and Exif Data

### ISSUE THREAD

**Issue by anystar** [joberthel/fastify-modern-images#7]
Could you please implement the annoying handling of rotation and exif data? See this Stack overflow as an example

https://stackoverflow.com/questions/48716266/sharp-image-library-rotates-image-when-resizing 

Perhaps a sane default on line 139 would be to call .withMetadata() before outputting?

**Comment by joberthel** [comment]
I had time to look into that issue. I decided to implement a rotation parameter, which can be added to the url:

e.g. `.../test.jpg=rotation=45` or `.../test.jpg=r=45`.

If no rotation is specified in the URL it will rotate based on the orientation, which is defined in the EXIF metadata.

I decided against the solution using `.withMetadata()` because it is against the purpose of this library. I wan't the image size to be as small as possible. Also it could contain private information like the geo location.
